### PR TITLE
fix phpunit errors

### PR DESCRIPTION
**Pull request by br0kk0l1**
I usually get these annoying erros about count() when running the tests and they spam stderr so i can't see the results of the test without scrolling up for what feels like a year, only to maybe miss it and see the previous results or something. I would just `make test 2> /dev/null` but then I'd miss errors when there were some that were triggered by my code, so that wasn't really a great solution either..

So here's a fix that applies a patch to phpunit on `make composer`

I hope this doesn't break anything for anybody (there's dependency on git, which could be switched to patch, but I'm not actually sure if that would be better...) and it's only a hacky workaround to the underlying problem of outdated vendor libraries, but in case we all have this problem and it solves it for everybody, I'd vote to merge this into main anyway

Props to @ishifoev for pointing me to the phpunit patch

`make distclean && make` to apply it, `make test` to see it in action

### CODE REVIEW

**Review by Triantafullenia-Doumani — APPROVED** [review]
It works well for me, good job

**Comment by ylebre** [comment]
The js/vendor/simplyedit removal doesn't seem to be part of this issue, right? Those were in there for the planned UI screens in the app (to show invitiations etc).

**Comment by br0kk0l1** [comment]
> The js/vendor/simplyedit removal doesn't seem to be part of this issue, right? Those were in there for the planned UI screens in the app (to show invitiations etc).

Yeah no, that must have happened when running `make distclean`. That shouldn't be in the commit. But that seems like something to be fixed in the Makefile as well

**Comment by br0kk0l1** [comment]
so this should revert the removal of simplyedit and make it so `make distclean` does not delete it anymore.
ideally we should probably do it the other way round, adding simplyedit as a dependency in npm or composer or something so it gets pulled in on `make` instead of preventing it from getting removed by `make distclean`

**Review by michielbdejong — APPROVED** [review]

**Review by ishifoev — APPROVED** [review]
Honestly we are talking with Ben. This error have a problem and we find solution in Github with update version. I think this is not bad and maybe someone would like change locally.

**Review by ylebre — APPROVED** [review]

**Pull request merged**
