### PR TITLE
Include Federated share provider parent class

### PR DESCRIPTION
**Pull request by MahdiBaghbani**

### CODE REVIEW

**Review by MahdiBaghbani — COMMENTED** [review]
I think everything is fine also we are using the `use OCA\ScienceMesh\AppInfo\ScienceMeshApp;` in the parent class.

**Review by mrvahedi68 — APPROVED** [review]
LGTM!

**Review by parhamin2010 — APPROVED** [review]
It looks good for me!

**Comment by MahdiBaghbani** [comment]
`use OCA\ScienceMesh\AppInfo\ScienceMeshApp;` doesn't exist on `ScienceMeshShareProvider.php`.
It doesn't show any errors and works as it should, But it is probably better if I add it to the file just in case

**Pull request merged**
