### PR TITLE
Admin Settings

### PR DESCRIPTION
**Pull request by parhamin2010**
Fix
https://github.com/pondersource/sciencemesh-php/issues/121

### CODE REVIEW

**Comment by parhamin2010** [comment]
admin_settings
Here's the feature.

**Comment by michielbdejong** [comment]
> we need to reopen the discussion about making them both read-only

-> https://github.com/pondersource/sciencemesh-php/issues/121#issuecomment-1376998380

**Comment by michielbdejong** [comment]
@parhamin2010 can you ping me on Slack when you have this PR ready for re-review? Thanks!

**Comment by parhamin2010** [comment]
Michiel, Please review it?

**Pull request merged**
