### PR TITLE
Update lint task #14

### PR DESCRIPTION
**Pull request by ishifoev**
There are task with make lint fix and make lint check. #14

### CODE REVIEW

**Comment by michielbdejong** [comment]
I tried this out but get:
```
root@3d1f1f52a1e6:/var/www/html/apps/sciencemesh# make lint-check
/var/www/html/apps/sciencemesh/vendor/bin/php-cs-fixer fix --dry-run --diff
make: /var/www/html/apps/sciencemesh/vendor/bin/php-cs-fixer: Command not found
make: *** [Makefile:59: lint-check] Error 127
```

**Review by michielbdejong — CHANGES_REQUESTED** [review]
Looks great! I couldn't get it to run, though.
Can you add instructions in the readme for how to run `make lint-check`?

**Review by Triantafullenia-Doumani — APPROVED** [review]

**Review by michielbdejong — COMMENTED** [review]
I think the step `apt install composer` is missing?

**Review by michielbdejong — COMMENTED** [review]
"How to use Lint for coverage tests" looks like it should be a header, not a bullet point?

**Review by michielbdejong — COMMENTED** [review]
Is the command `make:lint-check` working for both of you?
Shouldn't the `:` be a space?
I see this:
```sh
root@3d1f1f52a1e6:/var/www/html/apps/sciencemesh# make:lint-check
bash: make:lint-check: command not found
root@3d1f1f52a1e6:/var/www/html/apps/sciencemesh# make lint-check
/var/www/html/apps/sciencemesh/vendor/bin/php-cs-fixer fix --dry-run --diff
[...]
```

**Comment by ishifoev** [comment]
@michielbdejong Can you try again to remove the double point?

**Review by michielbdejong — APPROVED** [review]
lgtm if @Triantafullenia-Doumani also has it working on her computer

**Pull request merged**
