### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by michielbdejong**
Working with @parhamin2010 and @mirekys

### CODE REVIEW

**Comment by navid-dada** [comment]
I tried to check the PR and meanwhile a critical point is understood. there is no invitation-accept process designed in the new UI.
we can generate the invitation token but there is no textbox or input to paste the token and finalize the connection.

**Comment by michielbdejong** [comment]
> there is no textbox or input to paste the token and finalize the connection

Correct. Well, the page still exists but there no longer is a navigation menu item pointing to it.
This is because the only valid way to accept an invite is through https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=cern.ch
This redirects to https://cloud.pondersource.org/index.php/apps/sciencemesh/accept?token=asdf&providerDomain=cern.ch
And there, we concluded that the "user@host" input box is useless, it's too complex for the user, it should be a hidden form field, automatically populated from the URL query string.

**Comment by michielbdejong** [comment]
This was a design decision from our design brainstorm session with @mirekys

**Comment by michielbdejong** [comment]
Like this: https://files.gitter.im/634ea5646da03739849e00df/HxUX/Screenshot-2023-02-03-at-15.11.31.jpg

**Comment by navid-dada** [comment]
So the current UI is not similar to the image that you attached.

**Comment by parhamin2010** [comment]
image
Last commit

**Review by navid-dada — APPROVED** [review]

**Review by navid-dada — APPROVED** [review]

**Pull request merged**
