### PR TITLE
Draft: add other remote results to sciencemesh contact search results

### PR DESCRIPTION
**Pull request by mrvahedi68**
Related to: https://github.com/pondersource/sciencemesh-php/issues/183

### CODE REVIEW

**Comment by mrvahedi68** [comment]
rebased and fixed.
@MahdiBaghbani

**Comment by MahdiBaghbani** [comment]
Share from NC to OC works, 

Screenshot from 2023-04-25 21-59-59

although there is one error that needs to be checked.
is it related to our app?

- [ ] resolve this error: 

```json
{
  "reqId": "cWa9BVyflVfX0wrXvAfX",
  "level": 3,
  "time": "2023-04-25T18:22:14+00:00",
  "remoteAddr": "172.18.0.9",
  "user": "marie",
  "app": "PHP",
  "method": "POST",
  "url": "/index.php/apps/files_sharing/api/externalShares",
  "message": "Undefined index: password at /var/www/html/apps/files_sharing/lib/External/Storage.php#92"
}
```

Sharing from the local user in ownCloud to other local users works without problems.
in this case, marie shared with mahdi.

Screenshot from 2023-04-25 22-01-04

**Review by MahdiBaghbani — APPROVED** [review]
It is good to merge.

**Comment by mrvahedi68** [comment]
> Share from NC to OC works,
> 
> Screenshot from 2023-04-25 21-59-59
> 
> although there is one error that needs to be checked. is it related to our app?
> 
> * [ ]  resolve this error:
> 
> ```json
> {
>   "reqId": "cWa9BVyflVfX0wrXvAfX",
>   "level": 3,
>   "time": "2023-04-25T18:22:14+00:00",
>   "remoteAddr": "172.18.0.9",
>   "user": "marie",
>   "app": "PHP",
>   "method": "POST",
>   "url": "/index.php/apps/files_sharing/api/externalShares",
>   "message": "Undefined index: password at /var/www/html/apps/files_sharing/lib/External/Storage.php#92"
> }
> ```
> 
> Sharing from the local user in ownCloud to other local users works without problems. in this case, marie shared with mahdi.
> 
> Screenshot from 2023-04-25 22-01-04

**This error does not belong to this PR. We don't have any changes in this section.**

**Pull request merged**
